# Generated by Django 3.2.9 on 2022-10-27 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now, max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreview',
            name='session',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
