# Generated by Django 3.2.9 on 2022-10-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221027_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
    ]
