# Generated by Django 3.2.9 on 2022-10-28 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productreview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(blank=True, max_length=800, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Please input your comment!')]),
        ),
    ]
