# Generated by Django 3.2.9 on 2022-10-28 01:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productreview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now, max_length=800, validators=[django.core.validators.MinLengthValidator(10, 'Your comment must be longer than that!')]),
            preserve_default=False,
        ),
    ]
